data_root_directory: /sise/assafzar-group/assafzar/metalspy/TNBC-metals-data
experiments_root_dir_results: ./results/yeo_johnson_cv_train_eval
seeds:
  - 11
  - 19
  - 21
  - 22
  - 31
  - 36
  - 38
  - 54
  - 67
  - 82
  - 85
  - 88
  - 92
  - 94
  - 96
  - 112
  - 116
  - 140
  - 148
  - 156
  - 161
  - 177
  - 178
  - 212
  - 223
  - 225
  - 240
  - 242
  - 249
  - 276
  - 289
  - 293
  - 294
  - 300
  - 306
  - 309
  - 311
  - 320
  - 338
  - 342
  - 349
  - 358
  - 372
  - 373
  - 374
  - 382
  - 395
  - 418
  - 440
  - 444
  - 445
  - 465
  - 479
  - 480
  - 492
  - 494
  - 526
  - 567
  - 569
  - 586
  - 596
  - 600
  - 602
  - 606
  - 620
  - 633
  - 637
  - 641
  - 645
  - 647
  - 664
  - 689
  - 697
  - 708
  - 748
  - 753
  - 777
  - 794
  - 804
  - 812
  - 828
  - 831
  - 843
  - 858
  - 861
  - 875
  - 889
  - 891
  - 894
  - 897
  - 904
  - 917
  - 947
  - 962
  - 982
  - 983
  - 985
  - 987
  - 990
  - 998